name: Build libavif DLL (Windows)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows-dll:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        # 如果你的 libavif fork 依赖特定的外部子模块 (ext)，可能需要添加 submodules: true
        # with:
        #   submodules: true # 取消注释，如果需要子模块

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Install NASM
        run: choco install nasm -y

      - name: Add NASM to PATH
        run: echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Configure CMake (DLL)
        run: |
          cmake -S . -B build-shared -G Ninja `
            -DBUILD_SHARED_LIBS=ON `
            -DCMAKE_BUILD_TYPE=Release `
            -DAVIF_LIBYUV=LOCAL `
            -DAVIF_CODEC_AOM=LOCAL `
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON

      - name: Build DLL
        run: |
          cmake --build build-shared --config Release --parallel

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: libavif-dll-windows
          path: |
            build-shared/**/*.dll
          # build-shared/**/*.lib
          # build-shared/**/*.pdb